### ISSUE TITLE
Installation of this project

### ISSUE THREAD

**Issue by vijaygopalbalasa** [Regish/BE-8SemWork#1]
Hi sir,
I have been learning Machine learning and Image processing. I am still at the beginner level, I wanted to work on this project. How can I install and run this application? Does the project come under the Java domain? Can you please update the guide to help me. 

Thanks :-)

**Comment by Regish** [comment]
Hi Vijay, 

Glad to hear that you are interested to work on this project :)
Actually this was developed by my friends and I for our University project.
So, it is not up-to the mark of professional standards.

It was written with Java, but it would fall under "image processing" domain.

I'll add an Installation guide and will update you soon.

Thanks.

**Comment by Regish** [comment]
Hi Vijay,

I've added a new Mark Down file "InstallationGuide.md".
It contains all the steps to setup this project in Eclipse IDE on Windows.

I hope this would help.
And I'll close this issue for now.

Thanks.
